#!/bin/bash
# Interactive setup for llm-wiki personal assistant
# Usage: bash setup.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== llm-wiki Setup ==="
echo ""

# --- Prerequisites ---
echo "Checking prerequisites..."
missing=0

if command -v python3 &>/dev/null; then
    py_version=$(python3 --version 2>&1 | grep -oP '\d+\.\d+')
    echo "  Python: $(python3 --version)"
else
    echo "  Python: NOT FOUND (need 3.13+)"
    missing=1
fi

if command -v claude &>/dev/null; then
    echo "  Claude Code: $(claude --version 2>/dev/null || echo 'found')"
else
    echo "  Claude Code: NOT FOUND"
    echo "    Install: https://docs.anthropic.com/en/docs/claude-code"
    missing=1
fi

if command -v obsidian &>/dev/null; then
    echo "  Obsidian CLI: found"
else
    echo "  Obsidian CLI: NOT FOUND (optional — needed for vault queries)"
fi

if [ "$missing" -eq 1 ]; then
    echo ""
    echo "Missing required tools. Install them and re-run setup."
    exit 1
fi
echo ""

# --- Configuration ---
echo "Configuration"
echo "============="
echo ""

read -rp "Vault path [~/Documents/Day to day]: " vault_path
vault_path="${vault_path:-$HOME/Documents/Day to day}"
# Expand tilde
vault_path="${vault_path/#\~/$HOME}"

read -rp "Vault name for Obsidian CLI [$(basename "$vault_path")]: " vault_name
vault_name="${vault_name:-$(basename "$vault_path")}"

read -rp "Assistant name [Jarvis]: " assistant_name
assistant_name="${assistant_name:-Jarvis}"

read -rp "Credentials file [$HOME/.config/jarvis/credentials.env]: " creds_file
creds_file="${creds_file:-$HOME/.config/jarvis/credentials.env}"
creds_file="${creds_file/#\~/$HOME}"

echo ""

# --- Generate jarvis.conf ---
echo "Generating jarvis.conf..."
cat > "$REPO_DIR/jarvis.conf" <<CONF
# Jarvis Configuration — generated by setup.sh
JARVIS_VAULT_PATH="$vault_path"
JARVIS_VAULT_NAME="$vault_name"
JARVIS_ASSISTANT_NAME="$assistant_name"
JARVIS_CREDENTIALS_FILE="$creds_file"
CONF
echo "  Created: jarvis.conf"

# --- Generate vault-config.md ---
if [ ! -f "$REPO_DIR/vault-config.md" ]; then
    echo "Generating vault-config.md from template..."
    sed -e "s|{{VAULT_PATH}}|$vault_path|g" \
        -e "s|{{VAULT_NAME}}|$vault_name|g" \
        "$REPO_DIR/vault-config.md.template" > "$REPO_DIR/vault-config.md"
    echo "  Created: vault-config.md"
    echo "  >> Customize this file to map your vault's folder structure, tags, and key files."
else
    echo "  vault-config.md already exists — skipping (edit manually if needed)"
fi

# --- Credentials template ---
creds_dir="$(dirname "$creds_file")"
if [ ! -f "$creds_file" ]; then
    echo "Creating credentials template..."
    mkdir -p "$creds_dir"
    cp "$REPO_DIR/credentials.env.example" "$creds_file"
    echo "  Created: $creds_file"
    echo "  >> Fill in your API keys and tokens."
else
    echo "  Credentials file already exists — skipping"
fi

# --- Python venv ---
echo ""
echo "Setting up Python environment..."
cd "$REPO_DIR/scripts"
if [ ! -d ".venv" ]; then
    python3 -m venv .venv
    echo "  Created virtual environment"
fi
.venv/bin/pip install -q -r requirements.txt
echo "  Dependencies installed"
cd "$REPO_DIR"

# --- Generate systemd units ---
echo ""
echo "Generating systemd service files from templates..."
for template in "$REPO_DIR/systemd"/jarvis-*.service.template; do
    [ -f "$template" ] || continue
    name="$(basename "$template" .template)"
    sed -e "s|@@REPO_DIR@@|$REPO_DIR|g" \
        -e "s|@@HOME@@|$HOME|g" \
        -e "s|@@CREDENTIALS@@|$creds_file|g" \
        "$template" > "$REPO_DIR/systemd/$name"
    echo "  Generated: $name"
done

# --- Generate .claude/settings.json ---
echo ""
echo "Generating Claude Code permissions..."
mkdir -p "$REPO_DIR/.claude"
# Use tilde for portability in settings.json
vault_tilde="${vault_path/#$HOME/~}"
sed -e "s|@@VAULT_PATH@@|$vault_tilde|g" \
    "$REPO_DIR/.claude/settings.json.template" > "$REPO_DIR/.claude/settings.json"
echo "  Created: .claude/settings.json"

# --- Create _llm directory structure ---
echo ""
echo "Ensuring vault _llm directory structure..."
for dir in _llm _llm/status _llm/reviews _llm/daily _llm/data _llm/state; do
    mkdir -p "$vault_path/$dir"
done
echo "  Created: _llm/ directories in vault"

# --- Install systemd units ---
echo ""
read -rp "Install systemd units? (y/N): " install_systemd
if [[ "$install_systemd" =~ ^[Yy] ]]; then
    bash "$REPO_DIR/systemd/install.sh"
fi

# --- Done ---
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Edit vault-config.md to map your vault's structure"
echo "  2. Fill in credentials: $creds_file"
if [[ ! "$install_systemd" =~ ^[Yy] ]]; then
    echo "  3. Install systemd units: bash systemd/install.sh"
    echo "  4. Enable timers: systemctl --user daemon-reload && systemctl --user enable --now jarvis-daily.timer"
else
    echo "  3. Enable timers: systemctl --user enable --now jarvis-daily.timer"
fi
echo "  5. Test: ./scripts/run-jarvis.sh daily-briefing"
echo ""
echo "Docs: see README.md for full guide"
